- name: Updating the index of package and upgrading
  hosts: servers
  become: true
  tasks:
    - name: Updating the package index
      apt:
        update_cache: yes
    
    - name: Upgrade the package
      apt:
        upgrade: yes

- name: Download docker script and install docker using it 
  hosts: servers
  become: true
  tasks:
    - name: download docker script
      get_url:
        url: https://get.docker.com
        dest: /tmp/test-docker.sh
    - name: Install docker using the script downloaded earlier
      command: sh /tmp/test-docker.sh

- name: Make a user member of docker group and run hello-world
  hosts: servers
  become: yes
  tasks:
    - name: Make a user member of docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
    - name: Run a hello-world container
      command: docker run hello-world
